### ISSUE TITLE
如果有标题有四个, 是否可以让其中两个关联

### ISSUE THREAD

**Issue by ChunzhuXi** [wwmz/WMZDropDownMenu#1]
如果有标题有四个, 是否可以让其中两个关联

**Comment by wwmz** [comment]
两个选中不受其他标题选中影响是吗 
/*
*是否关联 其他标题 即选中其他标题 此标题会不会取消选中状态 default YES 取消，互不关联
*/
- (BOOL)menu:(WMZDropDownMenu *)menu dropIndexPathConnectInSection:(NSInteger)section;
这个代理让这两个标题返回NO 其他返回YES就行

**Comment by ChunzhuXi** [comment]
就是有四个标题, 类型,  综合, 价格, 销量,   我想价格和销量是相互关联的, (BOOL)menu:(WMZDropDownMenu *)menu dropIndexPathConnectInSection:(NSInteger)section;
像这个代理这样设置,  如果我价格是选中状态,  之后选择类型, 和综合价格也是变成了未选中状态 ,  我想选择综合和类型的时候不影响 价格和销量,   但是价格和销量这两个不能同时选中

**Comment by wwmz** [comment]
好吧 你这种复杂交互的我没想过 晚些给你加个可以设置的代理方法 你觉得代理方法返回带标题下标的数组相互关联 怎么样

**Comment by wwmz** [comment]
新增代理
/*
*互斥的标题数组 即互斥不能同时选中 返回标题对应的section (配合关联代理使用更加)
*/
- (NSArray*)mutuallyExclusiveSectionsWithMenu:(WMZDropDownMenu *)menu

你(BOOL)menu:(WMZDropDownMenu *)menu dropIndexPathConnectInSection:(NSInteger)section;这个代理全部返回NO
然后使用这个代理 返回例如[@(2),@(3)]  就可以达到你想要的结果了

**Comment by ChunzhuXi** [comment]
好的, 谢谢啦
