### ISSUE TITLE
筛选框会遮挡menu

### ISSUE THREAD

**Issue by LiuWenYu93** [wwmz/WMZDropDownMenu#10]
![EE41233D-B875-4704-912B-6B6D7233E0E1](https://user-images.githubusercontent.com/20696426/71885258-f4211e80-3174-11ea-90fd-ca2ddbe8268c.png)
弹出的筛选框的y值跑到menu上面去了 ，下面是没展示筛选框
![59AFCF08-31C4-43AD-B0CA-86147C4EFC4A](https://user-images.githubusercontent.com/20696426/71885332-1e72dc00-3175-11ea-9821-e5740c723f3e.png)

**Comment by wwmz** [comment]
(注意：如果弹出的视图的y值不准确 你可以手动设置menu的menuOrignY属性) 我特意标注这句话了呢 

你这里的话应该是少了一个导航栏的高度 
设置这个属性就行了 menu.menuOrignY = 导航栏高度+CGRectGetMaxY(menu.frame) ，或者你可以自己调一下 这个属性就是弹出来的y坐标的值呢
