### ISSUE TITLE
您好～

### ISSUE THREAD

**Issue by Ella1201** [wwmz/WMZDropDownMenu#11]
請問可以利用這個套件做出"查看更多"的效果嗎(如附圖)？

1. 點擊”查看更多“
![螢幕快照 2020-02-03 下午3 32 52](https://user-images.githubusercontent.com/50972928/73633811-9102a900-469a-11ea-8033-0bf430fde5eb.png)

2.顯示第二個篩選畫面
![螢幕快照 2020-02-03 下午3 33 01](https://user-images.githubusercontent.com/50972928/73633810-9102a900-469a-11ea-9238-d57694bb8353.png)

謝謝～

參考網址：https://www.itread01.com/p/19856.html

**Comment by wwmz** [comment]
有点麻烦呢 需要我加上我找时间加好跟你说

**Comment by wwmz** [comment]
> 請問可以利用這個套件做出"查看更多"的效果嗎(如附圖)？
> 
> 1. 點擊”查看更多“
>    ![螢幕快照 2020-02-03 下午3 32 52](https://user-images.githubusercontent.com/50972928/73633811-9102a900-469a-11ea-8033-0bf430fde5eb.png)
> 
> 2.顯示第二個篩選畫面
> ![螢幕快照 2020-02-03 下午3 33 01](https://user-images.githubusercontent.com/50972928/73633810-9102a900-469a-11ea-9238-d57694bb8353.png)
> 
> 謝謝～
> 
> 參考網址：https://www.itread01.com/p/19856.html

更新了 有查看更多的功能了 详情看京东demo

**Comment by Ella1201** [comment]
感謝！！

**Comment by wwmz** [comment]
> 感謝！！

不客气 有点忙。。这两天才想起来还有这个还没写哈
