### ISSUE TITLE
Aspects冲突

### ISSUE THREAD

**Issue by Lazyloadingg** [wwmz/WMZDropDownMenu#12]
我的项目中引用的有`Aspects`框架，引入了`WMZDropDownMenu`后编译报错，查看后得知你在`WMZDropDownMenu`中手动导入了`Aspects `的文件，最终我的项目中`Aspects `相关的文件重复，建议不要在开源的项目中手动导入其他开源项目的文件，否则一旦有开发人员同时引入这两个开源项目就会报错，并且还很尴尬，只能选择性手动引入其中一个才能解决

**Comment by wwmz** [comment]
嗯嗯 好的

**Comment by shengguangdaren** [comment]
能自定义动效吗？或者自定义视图自己控制出现的动效

**Comment by wwmz** [comment]
额 暂时没开放这个接口出来呢   WMZDropMenuAnimal 这个类是动画类 你可以自己去修改一下呢 增添你的动画进去就可以了

**Comment by shengguangdaren** [comment]
嗯好的
