### ISSUE TITLE
如果筛选是中titleArr倒数第二个 怎么实现里面筛选列表是单选   可否editStyleForRowAtDropIndexPath在这个代理方法中实现？

### ISSUE THREAD

**Issue by YYDreams** [wwmz/WMZDropDownMenu#14]
![图片](https://user-images.githubusercontent.com/15007334/74916919-a64d3680-5401-11ea-820f-165ea7b81f9f.png)

**Comment by wwmz** [comment]
图片看不到呢 加我q 925457662 我看看

**Comment by YYDreams** [comment]
加了 同意一下
