### ISSUE TITLE
图片模糊

### ISSUE THREAD

**Issue by MingForce** [wwmz/WMZDropDownMenu#16]
下拉的小三角和箭头图片都很模糊。

**Comment by wwmz** [comment]
这图片你可以自己换你自己的 兄弟 我只是提供例子 你可以放你自己的图片进去的 看demo  在代理传进去

**Comment by wwmz** [comment]
> 下拉的小三角和箭头图片都很模糊。
@MingForce  你可以在代理里自定义传图片进去的  我demo只是个例子 图片什么的全是可以自定义换的

**Comment by MingForce** [comment]
> 下拉的小三角和箭头图片都很模糊。
> @MingForce 你可以在代理里自定义传图片进去的 我demo只是个例子 图片什么的全是可以自定义换的

哪个代理方法可以？我看你是在配置标题的时候把小三角图标传进去的。而且加载时只是用bundle加载，我不能用自己本地的图标

**Comment by MingForce** [comment]
好吧，看到了，你那个应该也能加载本地的小图标，嘿嘿

**Comment by wwmz** [comment]
> 好吧，看到了，你那个应该也能加载本地的小图标，嘿嘿

@{@"name":@"综合",@"normalImage":@"menu_dowm",@"selectImage":@"menu_up"}  本地图标可以传的  那些例子里有的 我是优先从bundle里拿 没有就从本地拿
