### ISSUE TITLE
缺少定义标题的方法

### ISSUE THREAD

**Issue by MingForce** [wwmz/WMZDropDownMenu#17]
比如我要清空之前的选项，我选中我定义的“不限”做为清空，但我不想标题显示“不限”，我要另一外名称比如“价格”，我想要换掉

**Comment by MingForce** [comment]
或者选中后，不要去更新标题的文字也好点，因为选中的文字可能比较长，然后你换行了，比较难看。5555555

**Comment by MingForce** [comment]
好累，看了一天了，有的可以固定标题比如“更多”，有些不能，搞不明白。

**Comment by MingForce** [comment]
更新选中状态，有设置不限，可以么？

**Comment by wwmz** [comment]
在Base类 


> 比如我要清空之前的选项，我选中我定义的“不限”做为清空，但我不想标题显示“不限”，我要另一外名称比如“价格”，我想要换掉

在base类
- (void)changeTitleConfig:(NSDictionary*)config withBtn:(WMZDropMenuBtn*)currentBtn{
    if (config[@"name"]) {
       [currentBtn setTitle:config[@"name"] forState:UIControlStateNormal];
    }
    [currentBtn setTitleColor:currentBtn.selectColor forState:UIControlStateNormal];
    [currentBtn setTitleColor:currentBtn.selectColor forState:UIControlStateSelected];
}
#pragma -mark 回复原来的标题和文字
- (void)changeNormalConfig:(NSDictionary*)config withBtn:(WMZDropMenuBtn*)currentBtn{
    [currentBtn setTitle:currentBtn.normalTitle forState:UIControlStateNormal];
    [currentBtn setTitleColor:currentBtn.normalColor forState:UIControlStateNormal];
    [currentBtn setTitleColor:currentBtn.normalColor forState:UIControlStateSelected];
}
你可以去把setTitle的方法注释掉 这样就不会改变标题了 或者判断字符串为某个值不改变标题就可以了
