### ISSUE TITLE
砖研了两天，无奈弃用

### ISSUE THREAD

**Issue by MingForce** [wwmz/WMZDropDownMenu#18]
1我的导航栏是不透明的，这个时候，筛选菜单原点y值写0或一个导航栏高度，都不对。
2筛选菜单数据不支持后面加载，有哪些选项我这边是通过网络请求返回的。
3数据耦合性太高了，这个我觉得这个可以放开，要展示什么数据是应该用的人自己决定。只要提供位置，和设置数据的接口就好了。

**Comment by wwmz** [comment]
> 1我的导航栏是不透明的，这个时候，筛选菜单原点y值写0或一个导航栏高度，都不对。
> 2筛选菜单数据不支持后面加载，有哪些选项我这边是通过网络请求返回的。
> 3数据耦合性太高了，这个我觉得这个可以放开，要展示什么数据是应该用的人自己决定。只要提供位置，和设置数据的接口就好了。

1 我已经写的很清楚 如果出现弹出y值错误 手动设置menu的menuOrignY属性 你设置成导航栏高度有再加上筛选高度的高度吗 请问 
2 我都说了支持后面 加载 有三个更新数据的实例方法 你是看不见吗 
3 这都耦合性高那就没办法了 我都把选中不改变标题的方法发给你了 你都不看的吗 
4 再见走好不送

**Comment by jmy10241024** [comment]
钻研, 老文盲了
