### ISSUE TITLE
是否支持刷新整个section数据的方法。

### ISSUE THREAD

**Issue by luckyczh** [wwmz/WMZDropDownMenu#19]
我的section下面有很多rows，但是我获取数据后遍历刷新row 最后下拉时还是只有一行

**Comment by wwmz** [comment]
> 我的section下面有很多rows，但是我获取数据后遍历刷新row 最后下拉时还是只有一行

你刷新的代码给我看看呢

**Comment by luckyczh** [comment]
dispatch_async(dispatch_get_main_queue(), ^{
            [self.menu updateData:self.brandArray AtDropIndexPathSection:0 AtDropIndexPathRow:0];
            [self.menu updateData:self.priceArray AtDropIndexPathSection:1 AtDropIndexPathRow:1];
            [self.paramArray enumerateObjectsUsingBlock:^(SearchConditionGoodsTypeParam * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
                [self.menu updateData:[obj.value componentsSeparatedByString:@","] AtDropIndexPathSection:2 AtDropIndexPathRow:idx];
            }];
        });

**Comment by luckyczh** [comment]
- (NSInteger)menu:(WMZDropDownMenu *)menu numberOfRowsInSection:(NSInteger)section{
    if (section == 0) {
        return 1;
    }
    if (section == 1) {
        return 2;
    }
    if (section == 2) {
        return self.paramArray.count;
    }
    return 0;
}

**Comment by luckyczh** [comment]
> > 我的section下面有很多rows，但是我获取数据后遍历刷新row 最后下拉时还是只有一行
> 
> 你刷新的代码给我看看呢

是刷新方法不对么

**Comment by wwmz** [comment]
你初始
if (section == 2) {
return self.paramArray.count;
}
中返回的数量 和传入的数组 对的上吗 如果你一开始就只传了一个 那么更新就只会更新一个呢

**Comment by luckyczh** [comment]
> 你初始
> if (section == 2) {
> return self.paramArray.count;
> }
> 中返回的数量 和传入的数组 对的上吗 如果你一开始就只传了一个 那么更新就只会更新一个呢

这个最开始肯定没数据啊，这个也是从服务器获取的数据

**Comment by LiuWenYu93** [comment]
我也是这个问题 你是怎么处理的
