### ISSUE TITLE
动态筛选

### ISSUE THREAD

**Issue by dslcoding** [wwmz/WMZDropDownMenu#2]
我的需求点击优惠活动来更新商家服务这个一栏的数据 ,可以实现吗？

![Jietu20191205-222818](https://user-images.githubusercontent.com/26846337/70245564-3e4b6480-17b1-11ea-9afe-6da1935a4ff7.jpg)

**Comment by wwmz** [comment]
看不到图片哦 你加我q图片发我看看

**Comment by dslcoding** [comment]
> 看不到图片哦 你加我q图片发我看看

我发你邮箱 了你注意查收一下925457662@qq.com

**Comment by wwmz** [comment]
可以的 跟二级联动是一样的 


/*
*点击方法
*/
- (void)menu:(WMZDropDownMenu *)menu didSelectRowAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath dataIndexPath:(NSIndexPath *)indexpath data:(WMZDropTree*)data{
    //获取所在列
    if (dropIndexPath.section == 6) {
        //获取第一行
        if (dropIndexPath.row  == 0) {
            if (indexpath.row == 0) {
                [menu updateData:@[@"1",@"2"] ForRowAtDropIndexPath:dropIndexPath];
            }else{
                [menu updateData:@[@"2",@"3",@"2",@"3",@"2",@"3",@"2",@"3"] ForRowAtDropIndexPath:dropIndexPath];
            }
        }
    }
}

**Comment by dslcoding** [comment]
> 可以的 跟二级联动是一样的
> 
> /*
> *点击方法
> */
> 
> * (void)menu:(WMZDropDownMenu *)menu didSelectRowAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath dataIndexPath:(NSIndexPath _)indexpath data:(WMZDropTree_)data{
>   //获取所在列
>   if (dropIndexPath.section == 6) {
>   //获取第一行
>   if (dropIndexPath.row  == 0) {
>   if (indexpath.row == 0) {
>   [menu updateData:@[@"1",@"2"] ForRowAtDropIndexPath:dropIndexPath];
>   }else{
>   [menu updateData:@[@"2",@"3",@"2",@"3",@"2",@"3",@"2",@"3"] ForRowAtDropIndexPath:dropIndexPath];
>   }
>   }
>   }
>   }

好的我明天试试。
