### ISSUE TITLE
设置默认选中，需要调什么

### ISSUE THREAD

**Issue by hongdong** [wwmz/WMZDropDownMenu#20]
默认选中，需要调什么

**Comment by wwmz** [comment]
这个我没放出来呢 你可以这么试一下 
数据里 isSelected设为YES
- (NSArray *)menu:(WMZDropDownMenu *)menu dataForRowAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath{ if (dropIndexPath.section == 0) {
 return @[@{@"name":@"综合排序",@"isSelected":@(YES)},@"评论数从高到低"];
 }

//自定义标题里 把标题的颜色改了
- (NSDictionary*)menu:(WMZDropDownMenu *)menu customTitleInSection:(NSInteger)section withTitleBtn:(WMZDropMenuBtn*)menuBtn{ if (section == 0) { [menu changeTitleConfig:@{} withBtn:menuBtn]; [menuBtn showLine:@{}]; } return @{}; }

**Comment by hongdong** [comment]
好，多谢

**Comment by Wilshion** [comment]
> 这个我没放出来呢 你可以这么试一下
> 数据里 isSelected设为YES
> 
> * (NSArray *)menu:(WMZDropDownMenu *)menu dataForRowAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath{ if (dropIndexPath.section == 0) {
>   return @[@{@"name":@"综合排序",@"isSelected":@(YES)},@"评论数从高到低"];
>   }
> 
> //自定义标题里 把标题的颜色改了
> 
> * (NSDictionary*)menu:(WMZDropDownMenu _)menu customTitleInSection:(NSInteger)section withTitleBtn:(WMZDropMenuBtn_)menuBtn{ if (section == 0) { [menu changeTitleConfig:@{} withBtn:menuBtn]; [menuBtn showLine:@{}]; } return @{}; }

此方式可行，不过希望后面能够开放哦
