### ISSUE TITLE
Demo里的YiTaoDemo设置效果错乱.

### ISSUE THREAD

**Issue by HYY666** [wwmz/WMZDropDownMenu#21]
Demo里的YiTaoDemo设置效果错乱.

**Comment by wwmz** [comment]
> Demo里的YiTaoDemo设置效果错乱.

图片看看呢 是什么样

**Comment by HYY666** [comment]
打开第一个下拉视图再点击关闭视图.之后第一个视图就打不开了.
打开第一个下拉视图再打开第四个右侧视图.只剩蒙板了.
第二个占位用的menutitle能够响应关闭事件.
······
