### ISSUE TITLE
MenuUICollectionView样式点击立即关闭

### ISSUE THREAD

**Issue by ShowMoolan** [wwmz/WMZDropDownMenu#23]
MenuUICollectionView样式默认点击之后还要点确定才会关闭，现在我想去掉确定和重置实现点击立即关闭。但是我配置closeWithTapAtDropIndexPath后，发现MenuUICollectionView变成多选了，怎样才能让它单选呢

**Comment by wwmz** [comment]
> MenuUICollectionView样式默认点击之后还要点确定才会关闭，现在我想去掉确定和重置实现点击立即关闭。但是我配置closeWithTapAtDropIndexPath后，发现MenuUICollectionView变成多选了，怎样才能让它单选呢

有个MenuEdit的代理 设置MenuEditOneCheck即可

**Comment by ShowMoolan** [comment]
> > MenuUICollectionView样式默认点击之后还要点确定才会关闭，现在我想去掉确定和重置实现点击立即关闭。但是我配置closeWithTapAtDropIndexPath后，发现MenuUICollectionView变成多选了，怎样才能让它单选呢
> 
> 有个MenuEdit的代理 设置MenuEditOneCheck即可

- (MenuEditStyle)menu:(WMZDropDownMenu *)menu editStyleForRowAtDropIndexPath:(WMZDropIndexPath*)dropIndexPath{
    return MenuEditOneCheck;
}
我这样设置了但是没用

**Comment by wwmz** [comment]
> > > MenuUICollectionView样式默认点击之后还要点确定才会关闭，现在我想去掉确定和重置实现点击立即关闭。但是我配置closeWithTapAtDropIndexPath后，发现MenuUICollectionView变成多选了，怎样才能让它单选呢
> > 
> > 
> > 有个MenuEdit的代理 设置MenuEditOneCheck即可
> 
> * (MenuEditStyle)menu:(WMZDropDownMenu _)menu editStyleForRowAtDropIndexPath:(WMZDropIndexPath_)dropIndexPath{
>   return MenuEditOneCheck;
>   }
>   我这样设置了但是没用

+我q 说明容易点 925457662

**Comment by wwmz** [comment]
> > > MenuUICollectionView样式默认点击之后还要点确定才会关闭，现在我想去掉确定和重置实现点击立即关闭。但是我配置closeWithTapAtDropIndexPath后，发现MenuUICollectionView变成多选了，怎样才能让它单选呢
> > 
> > 
> > 有个MenuEdit的代理 设置MenuEditOneCheck即可
> 
> * (MenuEditStyle)menu:(WMZDropDownMenu _)menu editStyleForRowAtDropIndexPath:(WMZDropIndexPath_)dropIndexPath{
>   return MenuEditOneCheck;
>   }
>   我这样设置了但是没用

有个自定义尾部的代理 我优化了一下你可以更新一下GitHub 传入nil为使用默认的 传入[UIView new]可以达到你不要底部的效果
 - (UIView *)menu:(WMZDropDownMenu *)menu userInteractionFootViewInSection:(NSInteger)section{
   if (section == 1) return [UIView new];
    return nil;
}
