### ISSUE TITLE
是否能满足网络请求加载 row=1 的数据

### ISSUE THREAD

**Issue by eliashsu** [wwmz/WMZDropDownMenu#24]
点击 row=0，网络请求 row=2 的数据源
或者不支持的话，是否有什么好的方案，可以满足改情况？

**Comment by wwmz** [comment]
> 点击 row=0，网络请求 row=2 的数据源
> 或者不支持的话，是否有什么好的方案，可以满足改情况？
不是可以update各个row的位置吗  网络请求完update一下？

**Comment by wwmz** [comment]
> 点击 row=0，网络请求 row=2 的数据源
> 或者不支持的话，是否有什么好的方案，可以满足改情况？

不是可以update各个row的位置吗 网络请求完update一下？
