### ISSUE TITLE
能否设置下拉菜单的宽度

### ISSUE THREAD

**Issue by iOSchuang** [wwmz/WMZDropDownMenu#25]
能否设置弹出视图的宽度，目前是与屏幕等宽

**Comment by wwmz** [comment]
> 能否设置弹出视图的宽度，目前是与屏幕等宽

没提供属性哈 我加个吧 
新增 wCustomDataViewRect
//自定义弹出视图的frame 配合弹出底部阴影frame使用
新增 wCustomShadomViewRect
//自定义弹出底部阴影的frame
使用方法
//currentRect是当前的frame
    .wCustomDataViewRectSet(^CGRect(CGRect currentRect) {
        currentRect.size.width = Menu_Width*0.8;
        currentRect.origin.x = 0.1*Menu_Width;
        return currentRect;
    })

**Comment by iOSchuang** [comment]
更新了吗？我明天试一下。感谢！你的几个库都挺好用，我几乎都用到了，哈哈哈
