### ISSUE TITLE
如何清除数据，从新获取一下数据。

### ISSUE THREAD

**Issue by dslcoding** [wwmz/WMZDropDownMenu#26]
如何清除数据源，重新获取一下数据。

**Comment by wwmz** [comment]
/*
*更新数据 下一列的数据
*/
- (BOOL)updateData:(NSArray*)arr ForRowAtDropIndexPath:(WMZDropIndexPath*)dropIndexPath;


/*
*更新所有位置的数据 section表示所在行 row表示所在列
*/
- (BOOL)updateData:(NSArray*)arr AtDropIndexPathSection:(NSInteger)section AtDropIndexPathRow:(NSInteger)row;

/*
*更新全局位置某个数据源的数据 可更换选中状态 显示文字等。。。 根据WMZDropTree 对应属性改变
*/
- (BOOL)updateDataConfig:(NSDictionary*)changeData AtDropIndexPathSection:(NSInteger)section AtDropIndexPathRow:(NSInteger)row AtIndexPathRow:(NSInteger)indexPathRow;


/*
*更新所有UI和数据
*/
- (void)updateUI;

**Comment by wwmz** [comment]
> 如何清除数据源，重新获取一下数据。

/*
*更新数据 下一列的数据
*/

(BOOL)updateData:(NSArray*)arr ForRowAtDropIndexPath:(WMZDropIndexPath*)dropIndexPath;
/*
*更新所有位置的数据 section表示所在行 row表示所在列
*/

(BOOL)updateData:(NSArray*)arr AtDropIndexPathSection:(NSInteger)section AtDropIndexPathRow:(NSInteger)row;
/*
*更新全局位置某个数据源的数据 可更换选中状态 显示文字等。。。 根据WMZDropTree 对应属性改变
*/

(BOOL)updateDataConfig:(NSDictionary*)changeData AtDropIndexPathSection:(NSInteger)section AtDropIndexPathRow:(NSInteger)row AtIndexPathRow:(NSInteger)indexPathRow;
/*
*更新所有UI和数据
*/

(void)updateUI;   这里的更新方法都可以用呢
