### ISSUE TITLE
嵌套问题

### ISSUE THREAD

**Issue by 979881765** [wwmz/WMZDropDownMenu#27]
筛选菜单作为CollectionView的头部, 而CollectionView又嵌套在UITableView中， 那代理中的inScrollView应该 传CollectionView还是UITableView ？

我分别都试过了，都不行，都是从屏幕顶部弹出来。

**Comment by wwmz** [comment]
> 筛选菜单作为CollectionView的头部, 而CollectionView又嵌套在UITableView中， 那代理中的inScrollView应该 传CollectionView还是UITableView ？
> 
> 我分别都试过了，都不行，都是从屏幕顶部弹出来。

//动态高度
- (CGFloat)popFrameY

设置这个代理呢 你可以自己调弹出位置的 动态的
