### ISSUE TITLE
我该如何获取两个列表中的结果，同时拿着两个结果去查询

### ISSUE THREAD

**Issue by dslcoding** [wwmz/WMZDropDownMenu#3]
我现在的问题是1.同时点击第一列（全广州）和第二列（租金），然后我选择3号线和500-1000这两个数据，现在是我要获取这个3号线和500-1000的结果去数据库里查。2.我点击3号线时能不能更新租金一列的数据或者是户型的数据。
![Jietu20191205-225940](https://user-images.githubusercontent.com/26846337/70247147-d9453e00-17b3-11ea-97d8-cfec8eac35e9.jpg)

**Comment by wwmz** [comment]
行 我明天开放个更新所有列和行的实例方法出来

**Comment by dslcoding** [comment]
好的，非常感谢。非常感谢。

**Comment by dslcoding** [comment]
> 行 我明天开放个更新所有列和行的实例方法出来

那问题1能实现吗？同时获取两个结果去查询

**Comment by dslcoding** [comment]
> 行 我明天开放个更新所有列和行的实例方法出来

那问题1是如何实现的，或者是说是怎么获取的

**Comment by dslcoding** [comment]
> 行 我明天开放个更新所有列和行的实例方法出来

如图：
![Jietu20191205-234600](https://user-images.githubusercontent.com/26846337/70250989-bb7ad780-17b9-11ea-90ed-41c511e69667.jpg)

**Comment by wwmz** [comment]
你可以用个数组 在外部点击代理里装一下？或者我给你个获取全部选中的代理方法吧

**Comment by dslcoding** [comment]
> 你可以用个数组 在外部点击代理里装一下？或者我给你个获取全部选中的代理方法吧

你给我一个能获取全部选中的代理方法吧！

**Comment by wwmz** [comment]
新增代理
/*
*获取所有选中的数据
*/
- (void)menu:(WMZDropDownMenu *)menu getAllSelectData:(NSArray*)selectData

**Comment by wwmz** [comment]
新增实例方法
/*
*更新所有位置的数据 section表示所在行 row表示所在列
*/
- (void)updateData:(NSArray*)arr AtDropIndexPathSection:(NSInteger)section AtDropIndexPathRow:(NSInteger)row;

**Comment by dslcoding** [comment]
> 新增实例方法
> /*
> *更新所有位置的数据 section表示所在行 row表示所在列
> */
> 
> * (void)updateData:(NSArray*)arr AtDropIndexPathSection:(NSInteger)section AtDropIndexPathRow:(NSInteger)row;

好的，谢谢 cocoapods也更新了吗？

**Comment by wwmz** [comment]
cocopods还没更新哦
