### ISSUE TITLE
如何开启tableViewCell菜单分割线的样式？

### ISSUE THREAD

**Issue by iT-Boyer** [wwmz/WMZDropDownMenu#30]

**Comment by wwmz** [comment]
> _No description provided._

可以试着在自定义的cell开启呢  return nil则使用默认的
- (UITableViewCell*)menu:(WMZDropDownMenu *)menu cellForUITableView:(WMZDropTableView*)tableView AtIndexPath:(NSIndexPath*)indexpath dataForIndexPath:(WMZDropTree*)model{
    tableView.separatorStyle = UITableViewCellSeparatorStyleSingleLine;
    return nil;
}

**Comment by iT-Boyer** [comment]
已解决，谢谢。
