### ISSUE TITLE
在多级列表中，如何在点击没有子级的菜单时，触发关闭下拉框。

### ISSUE THREAD

**Issue by iT-Boyer** [wwmz/WMZDropDownMenu#31]
研究了大神的代码，过程中遇到的两个问题，通过深挖源码，勉强解决了。
```objc
// 无子目录时，执行确认操作
        if (vmm.children.count == 0) {
            if ([menu respondsToSelector:@selector(confirmAction:)]) {
                [menu performSelector:@selector(confirmAction:) withObject:[UIButton new]]; //问题1
                [menu changeTitleConfig:@{@"name":vmm.name} withBtn:menu.selectTitleBtn];//问题2
            }
        }
```
暂时使用`confirmAction:`方法来实现。
遇到的两个问题：
1. 在头文件中没有开放出来的`-(void)confirmAction:(id)sender`确认方法.
2. 在上下推出下拉框样式中，强制使用`confirmAction:`方法关闭，导致标签显示为多选。
暂时通过调用：`changeTitleConfig: withBtn:`方法同步了选中的内容。
```objc
if ([self getTitleFirstDropWthTitleBtn:self.selectTitleBtn].showAnimalStyle == MenuShowAnimalLeft||
            [self getTitleFirstDropWthTitleBtn:self.selectTitleBtn].showAnimalStyle == MenuShowAnimalRight) {
            [self changeTitleConfig:@{@"name":self.selectTitleBtn.titleLabel.text} withBtn:self.selectTitleBtn];
        }else{
            WMZDropTree *tree = self.selectArr[0];
            [self changeTitleConfig:@{@"name":self.selectArr.count>1?@"多选":
                                          (tree.name?:self.selectTitleBtn.titleLabel.text)} withBtn:self.selectTitleBtn];
        }
```

**Comment by wwmz** [comment]
> 研究了大神的代码，过程中遇到的两个问题，通过深挖源码，勉强解决了。
> 
> ```objc
> // 无子目录时，执行确认操作
>         if (vmm.children.count == 0) {
>             if ([menu respondsToSelector:@selector(confirmAction:)]) {
>                 [menu performSelector:@selector(confirmAction:) withObject:[UIButton new]]; //问题1
>                 [menu changeTitleConfig:@{@"name":vmm.name} withBtn:menu.selectTitleBtn];//问题2
>             }
>         }
> ```
> 
> 暂时使用`confirmAction:`方法来实现。
> 遇到的两个问题：
> 
> 1. 在头文件中没有开放出来的`-(void)confirmAction:(id)sender`确认方法.
> 2. 在上下推出下拉框样式中，强制使用`confirmAction:`方法关闭，导致标签显示为多选。
>    暂时通过调用：`changeTitleConfig: withBtn:`方法同步了选中的内容。
> 
> ```objc
> if ([self getTitleFirstDropWthTitleBtn:self.selectTitleBtn].showAnimalStyle == MenuShowAnimalLeft||
>             [self getTitleFirstDropWthTitleBtn:self.selectTitleBtn].showAnimalStyle == MenuShowAnimalRight) {
>             [self changeTitleConfig:@{@"name":self.selectTitleBtn.titleLabel.text} withBtn:self.selectTitleBtn];
>         }else{
>             WMZDropTree *tree = self.selectArr[0];
>             [self changeTitleConfig:@{@"name":self.selectArr.count>1?@"多选":
>                                           (tree.name?:self.selectTitleBtn.titleLabel.text)} withBtn:self.selectTitleBtn];
>         }
> ```

你去看美团外卖的demo里面有的 下级分类数量为0的时候
直接调用 [menu closeWith:dropIndexPath row:indexpath.row data:data]; 就可以了

**Comment by iT-Boyer** [comment]
嗯，在demo中有`WMZDropDownMenu.h`开放了`closeWith:row:data:`方法
我是用的cocoapods集成的，目前版本还不支持，坐等升级下库版本。

**Comment by iT-Boyer** [comment]
本地更新了索引`pod update`,已经拿到最新版本。
