### ISSUE TITLE
更新菜单的内容，高度没有变化。

### ISSUE THREAD

**Issue by iT-Boyer** [wwmz/WMZDropDownMenu#32]
当`treeArr`根据条件变更，元素数不同。调用如下更新方式，无法根据不同的内容更新菜单的高度。
```objc
[self.menu updateData:treeArr AtDropIndexPathSection:section AtDropIndexPathRow:0];
```
请教下，使用什么方式可以同时适配高度？

**Comment by wwmz** [comment]
> 当`treeArr`根据条件变更，元素数不同。调用如下更新方式，无法根据不同的内容更新菜单的高度。
> 
> ```objc
> [self.menu updateData:treeArr AtDropIndexPathSection:section AtDropIndexPathRow:0];
> ```
> 
> 请教下，使用什么方式可以同时适配高度？

适配什么高度 列表的高度吗 这个高度还要动态变化吗 
你可以试着在数组里去改视图的高度 例如
    [menu.showView enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        if ([obj isKindOfClass:[WMZDropTableView class]]) {
            。。。
        }
    }];

**Comment by iT-Boyer** [comment]
使用图片描述下更新高度的场景：
商圈：有多个选项，商场：只有一个选项。
当切换到商场时，下次进入菜单的总高度高度只有一个选项的高度。这样切换到商圈时，需要更新菜单的高度。
![截屏2020-09-22 上午11 10 42](https://user-images.githubusercontent.com/4022953/93840822-53539e80-fcc4-11ea-9c13-9d5d6adab0cf.png)
我尝试在商圈/商场切换时调用下面的方法，没有作用。
```objc
//更新高度
[menu.showView enumerateObjectsUsingBlock:^(id _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
      if ([obj isKindOfClass:[WMZDropTableView class]]) {
           WMZDropTableView *tblview = (WMZDropTableView *)obj;
            tblview.frame = CGRectMake(tblview.frame.origin.x, tblview.frame.origin.y, tblview.frame.size.width, MAINHEIGHT*0.4);
    }
}];
//更新数据
[self.menu updateData:treeArr AtDropIndexPathSection:section AtDropIndexPathRow:0];
```

**Comment by iT-Boyer** [comment]
自定义headview时，实现头部高度时，出现偶现的问题：headview下面会多出等高的区域
![截屏2020-09-22 上午11 20 56](https://user-images.githubusercontent.com/4022953/93841322-cc072a80-fcc5-11ea-9cbb-680d3dafa975.png)

```
/**
 实现这个代理会出现问题，莫名多出头部高度，暂时用默认高度35
 */
- (CGFloat)menu:(WMZDropDownMenu *)menu heightForHeadViewAtDropIndexPath:(WMZDropIndexPath*)dropIndexPath
{
    NSDictionary *dic = self.menu.titleArr[dropIndexPath.section];
    NSString *name = [dic objectForKey:@"name"];
    if ([name hasPrefix:@"商圈"]) {
        return 40;
    }
    return 0;
}
```

**Comment by wwmz** [comment]
> 使用图片描述下更新高度的场景：
> 商圈：有多个选项，商场：只有一个选项。
> 当切换到商场时，下次进入菜单的总高度高度只有一个选项的高度。这样切换到商圈时，需要更新菜单的高度。
> ![截屏2020-09-22 上午11 10 42](https://user-images.githubusercontent.com/4022953/93840822-53539e80-fcc4-11ea-9c13-9d5d6adab0cf.png)
> 我尝试在商圈/商场切换时调用下面的方法，没有作用。
> 
> ```objc
> //更新高度
> [menu.showView enumerateObjectsUsingBlock:^(id _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
>       if ([obj isKindOfClass:[WMZDropTableView class]]) {
>            WMZDropTableView *tblview = (WMZDropTableView *)obj;
>             tblview.frame = CGRectMake(tblview.frame.origin.x, tblview.frame.origin.y, tblview.frame.size.width, MAINHEIGHT*0.4);
>     }
> }];
> //更新数据
> [self.menu updateData:treeArr AtDropIndexPathSection:section AtDropIndexPathRow:0];
> ```

我看了一下 我会自动适配高度的呀 你看那个赶集网demo 第一个和第二个 弹出来的视图高度是自动适配的

**Comment by iT-Boyer** [comment]
嗯，我看下赶集网的样式，是连个菜单下自适应的高度。
我想描述的是针对一个菜单下的`menu.showView`中的`tableView`根据内容自适应高度。
上述说的`商场`和`商圈`是更新这个`tableView`的数据源，但是高度没有自适应。

**Comment by wwmz** [comment]
> 嗯，我看下赶集网的样式，是连个菜单下自适应的高度。
> 我想描述的是针对一个菜单下的`menu.showView`中的`tableView`根据内容自适应高度。
> 上述说的`商场`和`商圈`是更新这个`tableView`的数据源，但是高度没有自适应，导致数据无法正常展示。
> ![test mp4](https://user-images.githubusercontent.com/4022953/93955957-8a3cb980-fd83-11ea-8f9a-6fc6ea1f4278.gif)
> 
> 为解决数据展示正常，想到了两种方法：
> 
> 1. 针对当前tableView实现自动适配高度。
> 2. 禁止自动适配，设置菜单最大高度。
>    针对方法2，有开放的属性的吗？

可以加下群 我这里没怎么看

**Comment by iT-Boyer** [comment]
## 方法一：
在初始化menu时，设置入参：固定下拉框的高度：
```objc
//自定义弹出视图frame
        .wCustomDataViewRectSet(^CGRect(CGRect currentRect) {
            currentRect.size.height = MAINHEIGHT*0.4;
            return currentRect;
        })

```
## 方法二：
动态更新dataView和showView中的tableView的高度
```objc
CGRect newFrame = self.menu.dataView.frame;
    newFrame.size.height = MAINHEIGHT*0.4;
    self.menu.dataView.frame = newFrame;
    [self.menu.showView enumerateObjectsUsingBlock:^(id _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        if ([obj isKindOfClass:[WMZDropTableView class]]) {
            WMZDropTableView *tblview = (WMZDropTableView *)obj;
            CGRect tbFrame = tblview.frame;
            tbFrame.size.height = MAINHEIGHT*0.4;
            tblview.frame = tbFrame;
        }
    }];
```
