### ISSUE TITLE
您好怎么通过自己定义的按钮调出侧边栏筛选呢？

### ISSUE THREAD

**Issue by HackRoy** [wwmz/WMZDropDownMenu#34]

**Comment by wwmz** [comment]
> _No description provided._

    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [menu.titleBtnArr enumerateObjectsUsingBlock:^(WMZDropMenuBtn*  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            if (idx == index && [obj isKindOfClass:[WMZDropMenuBtn class]]) {
                [obj sendActionsForControlEvents:UIControlEventTouchUpInside];
            }
        }];
    });

**Comment by HackRoy** [comment]
谢谢
