### ISSUE TITLE
为什么选完后,只能在menu显示一个选择值

### ISSUE THREAD

**Issue by GBChain** [wwmz/WMZDropDownMenu#36]
比如第一列选完,我选了A 显示A
第二列我选择了X,则A消失?

**Comment by wwmz** [comment]
> 比如第一列选完,我选了A 显示A
> 第二列我选择了X,则A消失?

- (BOOL)menu:(WMZDropDownMenu *)menu dropIndexPathConnectInSection:(NSInteger)section
default YES  返回NO就行了

**Comment by GBChain** [comment]
> > 比如第一列选完,我选了A 显示A
> > 第二列我选择了X,则A消失?
> 
> * (BOOL)menu:(WMZDropDownMenu *)menu dropIndexPathConnectInSection:(NSInteger)section
>   default YES  返回NO就行了

不行,选择后bar里不会被修改

**Comment by wwmz** [comment]
> > > 比如第一列选完,我选了A 显示A
> > > 第二列我选择了X,则A消失?
> > 
> > 
> > 
> > * (BOOL)menu:(WMZDropDownMenu *)menu dropIndexPathConnectInSection:(NSInteger)section
> >   default YES  返回NO就行了
> 
> 选择后bar里不会被修改,这个可以手动修改吗

bar里不会修改是啥意思
