### ISSUE TITLE
双击菜单按钮有问题

### ISSUE THREAD

**Issue by huangrun** [wwmz/WMZDropDownMenu#37]
在筛选菜单弹出的情况下，双击菜单按钮后状态异常，会出现灰色背景

**Comment by wwmz** [comment]
> 在筛选菜单弹出的情况下，双击菜单按钮后状态异常，会出现灰色背景

哪个demo里重现的呢

**Comment by huangrun** [comment]
很多都可以复现，比如第一个demo里点击综合，展开后，再连续点两下综合，就可以看到了

**Comment by huangrun** [comment]
由于时间紧急，我在- (void)menu:(WMZDropDownMenu *)menu didSelectTitleInSection:(NSInteger)section btn:(WMZDropMenuBtn*)selectBtn方法内加了按钮的连续点击屏蔽临时解决了，但是太不优雅了：

selectBtn.userInteractionEnabled = NO;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        selectBtn.userInteractionEnabled = YES;
    });

**Comment by wwmz** [comment]
> 由于时间紧急，我在- (void)menu:(WMZDropDownMenu _)menu didSelectTitleInSection:(NSInteger)section btn:(WMZDropMenuBtn_)selectBtn方法内加了按钮的连续点击屏蔽临时解决了，但是太不优雅了：
> 
> selectBtn.userInteractionEnabled = NO;
> dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
> selectBtn.userInteractionEnabled = YES;
> });

1.1.5已修复 内部增加标题点击间隔时间
