### ISSUE TITLE
都是单选下拉框，但是最后一个点击不消失？

### ISSUE THREAD

**Issue by lzc1022** [wwmz/WMZDropDownMenu#38]
![Simulator Screen Shot - iPhone 11 - 2021-05-13 at 16 15 35](https://user-images.githubusercontent.com/9947322/118098418-77582180-b406-11eb-8da9-6ca6d2e925eb.png)

**Comment by lzc1022** [comment]
![Simulator Screen Shot - iPhone 11 - 2021-05-13 at 16 35 54](https://user-images.githubusercontent.com/9947322/118100740-60ff9500-b409-11eb-8989-2d2abe6a5cf9.png)
这是第二个问题，点击列表，滑动出现的

**Comment by wwmz** [comment]
> ![Simulator Screen Shot - iPhone 11 - 2021-05-13 at 16 35 54](https://user-images.githubusercontent.com/9947322/118100740-60ff9500-b409-11eb-8989-2d2abe6a5cf9.png)
> 这是第二个问题，点击列表，滑动出现的

第一个问题 不是单选就选择了就会消失的 你要看你是不是还用了 /*
*WMZDropIndexPath上的内容点击 是否关闭视图 default YES
*/
- (BOOL)menu:(WMZDropDownMenu *)menu closeWithTapAtDropIndexPath:(WMZDropIndexPath*)dropIndexPath; 这个代理

**Comment by wwmz** [comment]
> ![Simulator Screen Shot - iPhone 11 - 2021-05-13 at 16 35 54](https://user-images.githubusercontent.com/9947322/118100740-60ff9500-b409-11eb-8989-2d2abe6a5cf9.png)
> 这是第二个问题，点击列表，滑动出现的

第二个问题 那个是可以自己调的 根据场景你自己调整 调用popFrameY 这个代理 返回动态的值即可

**Comment by lzc1022** [comment]
能不能把上述第二个问题的demo修改下，我做个参考

**Comment by wwmz** [comment]
> 能不能把上述第二个问题的demo修改下，我做个参考

//动态高度
- (CGFloat)popFrameY{
    CGFloat y = [self.tableView convertRect:[self.tableView rectForHeaderInSection:0] toView:[self.tableView superview]];
    return  y;
}  去调一下这个y值就可以啦

**Comment by lzc1022** [comment]
我尝试了，还是不行，很急！！！，求帮助

**Comment by wwmz** [comment]
> 我尝试了，还是不行，很急！！！，求帮助

？？你自己调一下啊。。。 你那应该就是在原来的基础上偏差了一个导航栏的距离 减去就行了啊

**Comment by lzc1022** [comment]
您QQ多少，我加您

**Comment by wwmz** [comment]
> 您QQ多少，我加您
925457662
