### ISSUE TITLE
弹出菜单，选中某项点确定后再去取消选中，点击空白处此时刚才的取消选中操作也生效了

### ISSUE THREAD

**Issue by huangrun** [wwmz/WMZDropDownMenu#39]
本项目Demo中的美团外卖示例，速度和全部筛选可以复现这个问题。

**Comment by wwmz** [comment]
> 本项目Demo中的美团外卖示例，速度和全部筛选可以复现这个问题。



> 本项目Demo中的美团外卖示例，速度和全部筛选可以复现这个问题。

已修复 pod暂未同步更新哈  github有点抽风又push不上来了

**Comment by huangrun** [comment]
好的，谢谢！麻烦空了更新下pod吧。

**Comment by wwmz** [comment]
> 好的，谢谢！麻烦空了更新下pod吧。

已更新至1.1.6
