### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by ysyuan24** [wwmz/WMZDropDownMenu#4]
我发现，放在tableViewHeader上时，下拉菜单只会显示在状态栏下方，而不是在tableViewHeader下方

**Comment by ysyuan24** [comment]
![WX20191210-143051](https://user-images.githubusercontent.com/17896423/70501692-be7b1c80-1b59-11ea-9d85-d23547cba070.png)

**Comment by wwmz** [comment]
看不见图片~ ~

**Comment by ysyuan24** [comment]
如果菜单放在页面其他位置上，我需要对应设置menuOrignY这个属性，是这样吗

**Comment by ysyuan24** [comment]
通过设置menuOrignY，已经解决了，谢谢

**Comment by wwmz** [comment]
你是放在哪个tableViewHeader上  我默认是sction第0个的 如果不是第0个你要传menu.tableViewHeadSection = section;

嗯嗯 不过menuOrignY按道理不需要你设置的。。。。

**Comment by ysyuan24** [comment]
其实我是用在UICollectionView的header，menu.tableViewHeadSection = section这个对我不知道是否不适用。
并且我在您的demo“一淘”上尝试，发现不管有没有使用menu.tableViewHeadSection = section，好像都没有作用，下拉菜单的y值还是一样从状态栏下方开始哦。

**Comment by wwmz** [comment]
- -原来你是collectionView啊。。。。。。我只自动适配了tableview的 = = 好吧 那你只能自己手动改一下menuOrignY了 也不难哈哈。。好像你已经解决了
不是 menu.tableViewHeadSection = section这个是如果section>0的时候才需要传的

**Comment by wwmz** [comment]
我找时间自动适配一下collectionView headview的

**Comment by ysyuan24** [comment]
谢谢
