### ISSUE TITLE
点击头部会重置

### ISSUE THREAD

**Issue by NONGFUSPRING** [wwmz/WMZDropDownMenu#41]
![github00007](https://user-images.githubusercontent.com/8274996/122351556-d0c0ec80-cf80-11eb-885c-9de6877cda2e.png)
先选择红色区域，头部标题会更改并收起，再次选择蓝色区域，再点击绿色区域，左侧弹框会重置！

顺便再说一下，后面再更新版本能添加个弹框收起时的代理 或者通知吗？

**Comment by wwmz** [comment]
> ![github00007](https://user-images.githubusercontent.com/8274996/122351556-d0c0ec80-cf80-11eb-885c-9de6877cda2e.png)
> 先选择红色区域，头部标题会更改并收起，再次选择蓝色区域，再点击绿色区域，左侧弹框会重置！
> 
> 顺便再说一下，后面再更新版本能添加个弹框收起时的代理 或者通知吗？

两级的话 如果右侧没有选中的 左侧就会重置  要想左侧点了就生效的话 就左侧点击完关闭即可  另外收起的代理是已经有了的
*监听关闭视图 可做修改标题文本和颜色的操作
*/
- (void)menu:(WMZDropDownMenu *)menu closeWithBtn:(WMZDropMenuBtn*)selectBtn   index:(NSInteger )index;
