### ISSUE TITLE
请问动画时间能否支持开发者修改

### ISSUE THREAD

**Issue by DevXieChao** [wwmz/WMZDropDownMenu#43]
#define menuAnimalTime 0.3 这个宏定义非常不友好

**Comment by wwmz** [comment]
> #define menuAnimalTime 0.3 这个宏定义非常不友好

属性太多了 貌似就没开放出来了 一般需要改到的时机不多吧

**Comment by DevXieChao** [comment]
0.3秒动画效果 产品说view显示有点慢了，要像美团app那样快一点、流畅一些

**Comment by wwmz** [comment]
> 0.3秒动画效果 产品说view显示有点慢了，要像美团app那样快一点、流畅一些

嗯 下次更新加上
