### ISSUE TITLE
Swift 不能用啊  菜单无法点击

### ISSUE THREAD

**Issue by lumangmang** [wwmz/WMZDropDownMenu#44]

**Comment by wwmz** [comment]
你没实现代理方法吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Devin ***@***.***&gt;
发送时间: 2021年12月22日 11:37
收件人: wwmz/WMZDropDownMenu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZDropDownMenu] Swift 不能用啊  菜单无法点击 (Issue #44)





 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lumangmang** [comment]
class ProductViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let param = MenuParam().wMainRadiusSet()(0)
            .wCellTitleFontSet()(.systemFont(ofSize: 14))
            .wCellSelectTitleFontSet()(.systemFont(ofSize: 14))
            .wCollectionViewCellSelectTitleColorSet()(HexRGB(0xF5F5F5))
            .wCollectionViewCellTitleColorSet()(HexRGB(0x7E7E7F))
            .wCollectionViewSectionRecycleCountSet()(3)
            .wMaxHeightScaleSet()(0.6)
            .wCellSelectShowCheckSet()(false)
        
        let menu = WMZDropDownMenu(frame: CGRect(x: 0, y: 0, width: kScreenWidth, height: 40), with: param)
        menu.delegate = self
        view.addSubview(menu)
    }
}


// MARK: - WMZDropMenuDelegate
extension ProductViewController: WMZDropMenuDelegate {
    func titleArr(in menu: WMZDropDownMenu) -> [Any] {
        return ["推荐", "销量", "价格", "积分", ["name": "车型", "normalImage":"menu_dowm","selectImage":"menu_up"]]
    }
    
    func menu(_ menu: WMZDropDownMenu, dataForRowAt dropIndexPath: WMZDropIndexPath) -> [Any] {
        if dropIndexPath.section == 4 {
            return ["ARCFOX 阿尔法T", "ARXFOX 阿尔法S", "ARCFOX 阿尔法S 华为HI"]
        }
        return []
    }
    
    func menu(_ menu: WMZDropDownMenu, titleForHeadViewAt dropIndexPath: WMZDropIndexPath) -> String {
        return dropIndexPath.section == 4 ? "请选择车型" : ""
    }
    
    func menu(_ menu: WMZDropDownMenu, heightAt dropIndexPath: WMZDropIndexPath, at indexpath: IndexPath) -> CGFloat {
        return 50
    }
    
    func menu(_ menu: WMZDropDownMenu, uiStyleForRowIndexPath dropIndexPath: WMZDropIndexPath) -> MenuUIStyle {
        return dropIndexPath.section == 4 ? MenuUITableView : MenuUINone
    }
    
    func menu(_ menu: WMZDropDownMenu, hideAnimalStyleForRowInSection section: Int) -> MenuHideAnimalStyle {
        return MenuHideAnimalTop
    }
    
    func menu(_ menu: WMZDropDownMenu, showAnimalStyleForRowInSection section: Int) -> MenuShowAnimalStyle {
        return MenuShowAnimalBottom
    }
    
    func menu(_ menu: WMZDropDownMenu, cellForUITableView tableView: WMZDropTableView, at indexpath: IndexPath, dataForIndexPath model: WMZDropTree) -> UITableViewCell {
        if tableView.dropIndex.section == 4 {
            var cell = tableView.dequeueReusableCell(withIdentifier: "GanJiTableViewCell")
            if cell == nil {
                cell = GanJiTableViewCell(style: .default, reuseIdentifier: "GanJiTableViewCell")
            }
            cell?.textLabel?.text = model.name
            cell?.textLabel?.textAlignment = .center
            return cell!
        }
        return UITableViewCell()
    }
    
    func menu(_ menu: WMZDropDownMenu, closeWithTapAt dropIndexPath: WMZDropIndexPath) -> Bool {
        return dropIndexPath.section == 4 ? true : false
    }
}

class GanJiTableViewCell: UITableViewCell {
    
}


完全按demo写的.但是菜单点击不响应

**Comment by lumangmang** [comment]
> 你没实现代理方法吧 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Devin ***@***.***&gt; 发送时间: 2021年12月22日 11:37 收件人: wwmz/WMZDropDownMenu ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [wwmz/WMZDropDownMenu] Swift 不能用啊 菜单无法点击 (Issue #44) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by wwmz** [comment]
> > 你没实现代理方法吧 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: Devin _**@**_._**> 发送时间: 2021年12月22日 11:37 收件人: wwmz/WMZDropDownMenu _**@**_.**_> 抄送: Subscribed _**@**_._**> 主题: Re: [wwmz/WMZDropDownMenu] Swift 不能用啊 菜单无法点击 (Issue #44) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>

缺少了交互方式 editstyle 还有数据源

**Comment by lumangmang** [comment]
> > > 你没实现代理方法吧 发自我的iPhone
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: Devin _**@**_._**> 发送时间: 2021年12月22日 11:37 收件人: wwmz/WMZDropDownMenu _**@**_.**_> 抄送: Subscribed _**@**_._**> 主题: Re: [wwmz/WMZDropDownMenu] Swift 不能用啊 菜单无法点击 (Issue #44) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> 缺少了交互方式 editstyle 还有数据源

我这个完全是按照这个demo写的啊  赶集网demo   这里也没有style  这个数据源是指什么？

#import "GanJiDemo.h"
@interface GanJiDemo ()
{
    WMZDropDownMenu *menu;
    BOOL showDetail;
}
@end

@implementation GanJiDemo

- (void)viewDidLoad {
    [super viewDidLoad];

    WMZDropMenuParam *param =
    MenuParam()
    .wMainRadiusSet(0)
    .wCollectionViewCellSelectTitleColorSet(MenuColor(0xFF513c))
    .wCollectionViewSectionRecycleCountSet(3)
    .wMaxHeightScaleSet(0.6)
    .wBorderShowSet(YES)
    .wBorderUpDownShowSet(YES)
    .wCellSelectShowCheckSet(NO);
    
    menu = [[WMZDropDownMenu alloc] initWithFrame:CGRectMake(0, Menu_NavigationBar, Menu_Width, 40) withParam:param];
    menu.delegate = self;
    [self.view addSubview:menu];
}


- (void)showData:(BOOL)show{
    if (showDetail == show) return;
    [menu updateData:show?@[@"不限",@"一室",@"两室",@"三室",@"四室及以上"]:nil AtDropIndexPathSection:2 AtDropIndexPathRow:1];
    CGFloat timeHeight = show?150:-150;
    CGRect dataViewRect = menu.dataView.frame;
    dataViewRect.size.height += timeHeight;
    menu.dataView.frame = dataViewRect;
    for (UICollectionView *collectionView in menu.showView) {
        if ([collectionView isKindOfClass:[UICollectionView class]]) {
            CGRect collectionViewRect = collectionView.frame;
            collectionViewRect.size.height += timeHeight;
            collectionView.frame = collectionViewRect;
            [collectionView reloadData];
        }
   }
  CGRect confirmViewRect = menu.confirmView.frame;
  confirmViewRect.origin.y += timeHeight;
  menu.confirmView.frame = confirmViewRect;
  showDetail = show;
}

- (NSArray*)titleArrInMenu:(WMZDropDownMenu *)menu{
    return @[
         @{@"name":@"全广州",@"normalImage":@"menu_dowm",@"selectImage":@"menu_up"},
         @{@"name":@"租金",@"normalImage":@"menu_dowm",@"selectImage":@"menu_up"},
         @{@"name":@"户型",@"normalImage":@"menu_dowm",@"selectImage":@"menu_up"},
         @{@"name":@"更多",@"normalImage":@"menu_dowm",@"selectImage":@"menu_up"},
    ];
}


- (NSInteger)menu:(WMZDropDownMenu *)menu numberOfRowsInSection:(NSInteger)section{
   if (section == 0){
        return 2;
    }else if (section == 2){
        return 2;
    }else if (section == 3){
        return 4;
    }

    return 1;
}

- (NSArray *)menu:(WMZDropDownMenu *)menu dataForRowAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath{
      if (dropIndexPath.section == 0){
          if (dropIndexPath.row == 0) return @[@"附近",@{@"name":@"区域"},@"地铁",@"学校"];
          if (dropIndexPath.row == 1) return @[@"1号线",@"2号线",@"3号线",@"4号线",@"5号线",
                                               @"1号线",@"2号线",@"3号线",@"4号线",@"5号线",
                                               @"1号线",@"2号线",@"3号线",@"4号线",@"5号线"];
      }else if (dropIndexPath.section == 1){
          return @[@"500元以下",@"500-1000",@"1000-1500",@"1500-2000",@"2500-3000",@"2500-3000",@"2500-3000",];
      }else if (dropIndexPath.section == 2){
           if (dropIndexPath.row == 0) return @[@"展开",@"收缩"];
      }else if (dropIndexPath.section == 3){
           if (dropIndexPath.row == 0) return @[@"不限",@"个人",@"经纪人",@"品牌公寓"];
           if (dropIndexPath.row == 1) return @[@"不限",@"安选"];
           if (dropIndexPath.row == 2) return @[@"不限",@"压一付一",@"压一付一",@"压一付一",@"压一付一",
                                                @"压一付一",@"压一付一",
                                                @"压一付一",@"压一付一",@"压一付一",@"压一付一",
                                                @"压一付一",@"压一付一",@"压一付一",@"压一付一"];
           if (dropIndexPath.row == 3) return @[@"不限",@"东",@"西",@"南",@"北",@"南北"];
      }
      return @[];
}

#define titleArr1 @[@"卧室",@"户型"]
#define titleArr2 @[@"房间来源",@"验真情况",@"房源特色",@"朝向"]
- (NSString *)menu:(WMZDropDownMenu *)menu titleForHeadViewAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath{
    if (dropIndexPath.section == 2){
        return titleArr1[dropIndexPath.row];
    }else if (dropIndexPath.section == 3){
        return titleArr2[dropIndexPath.row];
    }
    return nil;
}

- (NSInteger)menu:(WMZDropDownMenu *)menu countForRowAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath{
    return 3;
}
/*
*是否关联 其他标题 即选中其他标题 此标题会不会取消选中状态 default YES 
*/
- (BOOL)menu:(WMZDropDownMenu *)menu dropIndexPathConnectInSection:(NSInteger)section{
    return NO;
}

//- (NSDictionary*)menu:(WMZDropDownMenu *)menu  customTitleInSection:(NSInteger)section withTitleBtn:(WMZDropMenuBtn*)menuBtn{
//    if (section == 1) {
//        //选中中间清除其他所有选中
//        menuBtn.clear = YES;
//    }
//    return @{};
//}


/*
*互斥的标题数组 即互斥不能同时选中 返回标题对应的section (配合关联代理使用更加)
*/
//- (NSArray*)mutuallyExclusiveSectionsWithMenu:(WMZDropDownMenu *)menu{
//    return @[@(0),@(1)];
//}



- (CGFloat)menu:(WMZDropDownMenu *)menu heightAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath AtIndexPath:(NSIndexPath *)indexpath{
    if (dropIndexPath.section == 0 || dropIndexPath.section == 1) {
        return 50;
    }
    return 35;
}

- (MenuUIStyle)menu:(WMZDropDownMenu *)menu uiStyleForRowIndexPath:(WMZDropIndexPath *)dropIndexPath{
    if (dropIndexPath.section == 2||dropIndexPath.section == 3) {
        return MenuUICollectionView;
    }
    return MenuUITableView;
}

- (MenuHideAnimalStyle)menu:(WMZDropDownMenu *)menu hideAnimalStyleForRowInSection:(NSInteger)section{
    if (section==3) {
        return MenuHideAnimalLeft;
    }
    return MenuHideAnimalTop;
}

- (MenuShowAnimalStyle)menu:(WMZDropDownMenu *)menu showAnimalStyleForRowInSection:(NSInteger)section{
     if (section==3) {
          return MenuShowAnimalRight;
      }
      return MenuShowAnimalBottom;
}


- (UITableViewCell*)menu:(WMZDropDownMenu *)menu cellForUITableView:(WMZDropTableView *)tableView AtIndexPath:(NSIndexPath *)indexpath dataForIndexPath:(WMZDropTree *)model{
    if (tableView.dropIndex.section == 1) {
        GanJiTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"GanJiTableViewCell"];
        if (!cell) {
            cell = [[GanJiTableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"GanJiTableViewCell"];
        }
        cell.textLabel.text = model.name;
        cell.textLabel.textColor = model.isSelected?MenuColor(0xFF513c):MenuColor(0x666666);
        cell.textLabel.textAlignment = NSTextAlignmentCenter;
        return cell;
    }
    return nil;
}
- (BOOL)menu:(WMZDropDownMenu *)menu closeWithTapAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath{
    if (dropIndexPath.section == 0&&dropIndexPath.row == 1)  return YES;
    else if (dropIndexPath.section == 1) return YES;
    return NO;
}

- (void)menu:(WMZDropDownMenu *)menu customDefauultCollectionFootView:(WMZDropConfirmView *)confirmView{
    confirmView.showBorder = NO;
    confirmView.resetFrame = [NSValue valueWithCGRect:CGRectMake(0, 0,0 , confirmView.frame.size.height)];
    confirmView.confirmFrame = [NSValue valueWithCGRect:CGRectMake(0, 0,confirmView.frame.size.width , confirmView.frame.size.height)];
    confirmView.confirmBtn.backgroundColor = MenuColor(0xFF513c);
    [confirmView.confirmBtn setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
}



-  (void)menu:(WMZDropDownMenu *)menu didSelectRowAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath dataIndexPath:(NSIndexPath *)indexpath data:(WMZDropTree *)data{
    if (dropIndexPath.section == 0 && dropIndexPath.row == 1) {
        if (indexpath.row == 0) {
            [menu updateDataConfig:@{@"isSelected":@(NO)} AtDropIndexPathSection:2 AtDropIndexPathRow:0 AtIndexPathRow:2];
        }
    }else if (dropIndexPath.section == 2 && dropIndexPath.row == 0) {
        if (indexpath.row == 0) {
            data.isSelected?[self showData:YES]:[self showData:NO];
        }else{
            data.isSelected?[self showData:NO]:[self showData:YES];
        }
    }
}

@end


@implementation GanJiTableViewCell
@end

**Comment by lumangmang** [comment]
是不是这里的分类，我看好多方法都是用Aspects hook  或者其他一些方法冲突了  很容易和其他三方冲突    我看了一下菜单按钮的点击事件根本不执行

- (void)titleAction:(WMZDropMenuBtn*)sender{
    //点击代理
    if (self.delegate &&
        [self.delegate respondsToSelector:@selector(menu:didSelectTitleInSection:btn:)]) {
        [self.delegate menu:self didSelectTitleInSection:sender.tag-1000 btn:sender];
    }
    MenuWeakSelf(self)
    //点击标题网络请求
    if (self.delegate&&[self.delegate respondsToSelector:@selector(menu:didSelectTitleInSection:btn:networkBlock:)]) {
        [self.delegate menu:self didSelectTitleInSection:sender.tag-1000 btn:sender networkBlock:^{
            MenuStrongSelf(weakObject)
            [strongObject judgeBtnTitle:sender];
        }];
    }else{
        [self judgeBtnTitle:sender];
    }
}
这个方法不执行  导致无法点击，能否给点问题可能的原因

**Comment by wwmz** [comment]
> 是不是这里的分类，我看好多方法都是用Aspects hook 或者其他一些方法冲突了 很容易和其他三方冲突 我看了一下菜单按钮的点击事件根本不执行
> 
> * (void)titleAction:(WMZDropMenuBtn*)sender{
>   //点击代理
>   if (self.delegate &&
>   [self.delegate respondsToSelector:@selector(menu:didSelectTitleInSection:btn:)]) {
>   [self.delegate menu:self didSelectTitleInSection:sender.tag-1000 btn:sender];
>   }
>   MenuWeakSelf(self)
>   //点击标题网络请求
>   if (self.delegate&&[self.delegate respondsToSelector:@selector(menu:didSelectTitleInSection:btn:networkBlock:)]) {
>   [self.delegate menu:self didSelectTitleInSection:sender.tag-1000 btn:sender networkBlock:^{
>   MenuStrongSelf(weakObject)
>   [strongObject judgeBtnTitle:sender];
>   }];
>   }else{
>   [self judgeBtnTitle:sender];
>   }
>   }
>   这个方法不执行  导致无法点击，能否给点问题可能的原因

1 看下视图层 各个标题和menu的frame是否正常  2 看是不是响应链被其他拦截了

**Comment by lumangmang** [comment]
frame是正常的  menu都能正常显示   但就是不能点击    点击方法不执行

**Comment by wwmz** [comment]
> frame是正常的 menu都能正常显示 但就是不能点击 点击方法不执行

能显示不代表 响应链能传达 你建个空的控制器 放中间看一下 能不能点

**Comment by lumangmang** [comment]
- (void)tj_sendAction:(SEL)action to:(id)target forEvent:(UIEvent *)event{
    //判断时间差
    if (NSDate.date.timeIntervalSince1970 - self.tj_acceptEventTime < self.tj_acceptEventInterval) {
        return;
    }
    //记录时间
    if (self.tj_acceptEventInterval > 0) {
        self.tj_acceptEventTime = NSDate.date.timeIntervalSince1970;
    }
    //执行点击事件
    [self tj_sendAction:action to:target forEvent:event];
}

点击的时候  这个执行

**Comment by lumangmang** [comment]
建了个空项目  试了一下  可以

**Comment by wwmz** [comment]
> * tj_sendAction

这是为了防止重复点击加的 你去掉试试

**Comment by wwmz** [comment]
> 建了个空项目 试了一下 可以

那可能是跟你项目里的冲突了

**Comment by lumangmang** [comment]
去掉这个就可以了   但是我项目里没有对Button的点击进行拦截    建议还是去了吧 用处不是很大...  很容易冲突

**Comment by wwmz** [comment]
> 去掉这个就可以了 但是我项目里没有对Button的点击进行拦截 建议还是去了吧 用处不是很大... 很容易冲突

你建了空项目可以 不就是代表和你项目里冲突了吗。。。

**Comment by lumangmang** [comment]
再问个问题..
<img width="293" alt="image" src="https://user-images.githubusercontent.com/16453396/147181673-df6e79a0-bf2d-429d-8bf1-116494bac8a1.png">
这个选择的时候   如何让标题保持原来的不变

**Comment by wwmz** [comment]
> 再问个问题.. <img alt="image" width="293" src="https://user-images.githubusercontent.com/16453396/147181673-df6e79a0-bf2d-429d-8bf1-116494bac8a1.png"> 这个选择的时候 如何让标题保持原来的不变

1 设置标题的selectTitle值 和初始标题一致 2 实现menu:changeTitle:selectBtn:atDropIndexPath:dataIndexPath 自定义选中值

**Comment by lumangmang** [comment]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/16453396/147186375-39ead03f-5b98-492a-87d7-ca9f5fd12a83.png">
大佬...如何让第一个默认选中，有高亮颜色。。。

**Comment by wwmz** [comment]
> <img alt="image" width="304" src="https://user-images.githubusercontent.com/16453396/147186375-39ead03f-5b98-492a-87d7-ca9f5fd12a83.png">
> 
> 大佬...如何让第一个默认选中，有高亮颜色。。。

/// 手动选中标题 可做默认
- (void)defaultSelectIndex:(NSInteger)index;
