### ISSUE TITLE
是否考虑添加自定义collviewcell样式

### ISSUE THREAD

**Issue by YuStephen** [wwmz/WMZDropDownMenu#45]
我看项目里面只额外枚举了MenuUICollectionRangeTextField，是否考虑再加一个通用的customview，然后把注册方法暴露出来？

**Comment by wwmz** [comment]
> 我看项目里面只额外枚举了MenuUICollectionRangeTextField，是否考虑再加一个通用的customview，然后把注册方法暴露出来？

/// 自定义collectionViewCell内容
- (UICollectionViewCell*)menu:(WMZDropDownMenu *)menu cellForUICollectionView:(WMZDropCollectionView*)collectionView
    AtDropIndexPath:(WMZDropIndexPath*)dropIndexPath AtIndexPath:(NSIndexPath*)indexpath dataForIndexPath:(WMZDropTree*)model;

**Comment by YuStephen** [comment]
👌🏻
