### ISSUE TITLE
如何获取选择的数据？

### ISSUE THREAD

**Issue by lumangmang** [wwmz/WMZDropDownMenu#46]
大佬...请教2个问题
<img width="308" alt="image" src="https://user-images.githubusercontent.com/16453396/148884997-345cc45c-2f6e-4ff5-83bd-f4cf1613c0d5.png">

**Comment by wwmz** [comment]
> 大佬...请教2个问题 <img alt="image" width="308" src="https://user-images.githubusercontent.com/16453396/148884997-345cc45c-2f6e-4ff5-83bd-f4cf1613c0d5.png">

/// 获取所有选中
- (NSArray*)getAllSelectArr;
/// 获取某一行 所有列选中的数据
- (NSArray*)getSelectArrWithPathSection:(NSInteger)section;
/// 获取某一行 某一列选中的数据
- (NSArray*)getSelectArrWithPathSection:(NSInteger)section row:(NSInteger)row;         复选的话 可以在点击标题的代理里 根据 selectBtn.selectType == 1 来判断

**Comment by lumangmang** [comment]
这样不行..selectType判断不了，我意思 当我点击积分的时候 会升序 再次点击的时候会降序  怎么来判断当前是升序还是降序
![Uploading image.png…]()

**Comment by lumangmang** [comment]
<img width="162" alt="image" src="https://user-images.githubusercontent.com/16453396/148891447-e8fd2e6a-b347-4ad3-9671-15b2ab623ce7.png">

**Comment by lumangmang** [comment]
...   还有一个  怎么防止多点   比如当前是默认  我再点击默认的时候  不做网络请求
