### ISSUE TITLE
收起动画失效

### ISSUE THREAD

**Issue by Lyy1219** [wwmz/WMZDropDownMenu#48]
A->B->C，B页面集成，当跳转到C页面再返回B页面的时候，hide动画消失

**Comment by wwmz** [comment]
可手动关闭 closeView



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yy ***@***.***&gt;
发送时间: 2022年3月7日 17:50
收件人: wwmz/WMZDropDownMenu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZDropDownMenu] 收起动画失效 (Issue #48)





 
A-&gt;B-&gt;C，B页面集成的话
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lyy1219** [comment]
> 可以自己手动关闭 查看发iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人：yy ***@*** .***>发送时间：202年3月7日联合国17:50日：wwmz/WMZDropDownMenu ***@***.***>抄送：已订阅***@***.** *>主题: Re: [wwmz/WMZDropDownMenu] 收起动画类型 (Issue #48 ) A->B->C，B页面集成的话——直接回复此邮件，在GitHub上查看，或退订。使用适用于 iOS Android 的 GitHub Mobile 订阅您或您对通知进行分类。收到此消息是因为此消息。*** ID：***@***。

不行  动画已经消失了

**Comment by wwmz** [comment]
动画已经消失是什么意思？你在viewwillappeal里关闭不可以吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yy ***@***.***&gt;
发送时间: 2022年3月7日 17:56
收件人: wwmz/WMZDropDownMenu ***@***.***&gt;
抄送: WMZ ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [wwmz/WMZDropDownMenu] 收起动画失效 (Issue #48)





  
可以自己手动关闭 查看发iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人：yy @ .&gt;发送时间：202年3月7日联合国17:50日：wwmz/WMZDropDownMenu @.***@***.*** &gt;主题: Re: [wwmz/WMZDropDownMenu] 收起动画类型 (Issue #48 ) A-&gt;B-&gt;C，B页面集成的话——直接回复此邮件，在GitHub上查看，或退订。使用适用于 iOS Android 的 GitHub Mobile 订阅您或您对通知进行分类。收到此消息是因为此消息。* ID：@。
  
不行  动画已经消失了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lyy1219** [comment]
> closeView

就是说刚进入的时候是有动画的  然后我进入子页面后返回  收起动画就没有了

**Comment by Lyy1219** [comment]
https://user-images.githubusercontent.com/53418325/157014643-844276e7-d65a-4061-8a5f-25f319cd920c.MP4

**Comment by wwmz** [comment]
> RPReplay_Final1646648785.MP4

有时间加我q发个demo给我看看哈

**Comment by Lyy1219** [comment]
加q了  通过一下
