### ISSUE TITLE
宽度变短

### ISSUE THREAD

**Issue by Kingdon008** [wwmz/WMZDropDownMenu#50]
更新数据调用updateUI，使得titlescrollview的宽度变短

**Comment by wwmz** [comment]
> 更新数据调用updateUI，使得titlescrollview的宽度变短

没明白什么意思呢

**Comment by wwmz** [comment]
已修复

**Comment by wwmz** [comment]
已修复

**Comment by wwmz** [comment]
已修复

> 更新数据调用updateUI，使得titlescrollview的宽度变短

已修复
