### ISSUE TITLE
二级联动列表，怎么自定义第一tableview的宽度，而不是平分？

### ISSUE THREAD

**Issue by ShuangZiMoYin** [wwmz/WMZDropDownMenu#51]
二级联动，怎么设置第一级列表的宽度呢？方便加下qq吗？1223095071

**Comment by wwmz** [comment]
> 二级联动，怎么设置第一级列表的宽度呢？方便加下qq吗？1223095071

需要修改源码哦 目前是平分的  tableView.frame = CGRectMake(tmpTa?CGRectGetMaxX(tmpTa.frame):0, y, self.dataView.frame.size.width/dropArr.count, height-y); 查一下这个自己修改一下 width

**Comment by ShuangZiMoYin** [comment]
好的，我试试，哥，可以加下QQ吗？
