### ISSUE TITLE
控制器消失自动关闭视图有bug

### ISSUE THREAD

**Issue by Akulio** [wwmz/WMZDropDownMenu#54]
出现的情况是：比如筛选push进一个vc，然后返回后点击弹出某一列，再直接pop前面的控制器后 没有自动收起关闭

**Comment by wwmz** [comment]
> 出现的情况是：比如筛选push进一个vc，然后返回后点击弹出某一列，再直接pop前面的控制器后 没有自动收起关闭

使用手动关闭
