### ISSUE TITLE
发现了一个bug 。希望尽快解决！

### ISSUE THREAD

**Issue by MateenHJL** [wwmz/WMZDropDownMenu#58]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/75963611/199211390-8af5b713-901f-4187-ad85-4e7ab5ed9b86.png">
这段代码 导致控制器返回的时候会出现crash
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/75963611/199211492-4bbfc2c5-7133-4a7a-bf8d-842c791ebe94.png">

**Comment by wwmz** [comment]
> <img alt="image" width="1395" src="https://user-images.githubusercontent.com/75963611/199211390-8af5b713-901f-4187-ad85-4e7ab5ed9b86.png">
> 
> 这段代码 导致控制器返回的时候会出现crash
> <img alt="image" width="1388" src="https://user-images.githubusercontent.com/75963611/199211492-4bbfc2c5-7133-4a7a-bf8d-842c791ebe94.png">
没法重现哦

**Comment by MateenHJL** [comment]
你这段代码是指当控制器即将移除的时候 就关闭你当前的视图？ 能弄个开关吗 这段代码

**Comment by wwmz** [comment]
> 你这段代码是指当控制器即将移除的时候 就关闭你当前的视图？ 能弄个开关吗 这段代码

哦哦 可以的 下个版本添加
