### ISSUE TITLE
拼多多demo中 筛选  输入最低和最高价格筛选 并实现menu:didConfirmAtSection:selectNoramelData:selectStringData:代理方法后  闪退

### ISSUE THREAD

**Issue by LiuWenYu93** [wwmz/WMZDropDownMenu#6]
![D1CCFAF4-C08B-48CA-82D8-4AFE5E1B2FFC](https://user-images.githubusercontent.com/20696426/71495203-a3ade500-2887-11ea-948d-91d023f81d67.png)
tree.name为空所以闪退

**Comment by LiuWenYu93** [comment]
![D1CCFAF4-C08B-48CA-82D8-4AFE5E1B2FFC](https://user-images.githubusercontent.com/20696426/71495230-c9d38500-2887-11ea-8b7a-e4d18300c3cd.png)

**Comment by wwmz** [comment]
好的 已修复 GitHub代码已更新

**Comment by LiuWenYu93** [comment]
![7C150637-9265-4B16-A1B7-0666583596E7](https://user-images.githubusercontent.com/20696426/71613247-3cbe6200-2be0-11ea-9e15-2a860c365de3.png)
输入的价格区间和选择的价格区间 如何做到互斥   点击上面时清空输入的价格区间

**Comment by wwmz** [comment]
点击上面时清空？是点击另一个清空吗？
/*
*互斥的标题数组 即互斥不能同时选中 返回标题对应的section (配合关联代理使用更加)
*/
- (NSArray*)mutuallyExclusiveSectionsWithMenu:(WMZDropDownMenu *)menu{
    return @[0,@(1)];
}

**Comment by LiuWenYu93** [comment]
我的意思是点击20万以下  输入的最低总价和最高总价数据清空 回复默认

**Comment by wwmz** [comment]
点击代理的时候更新数据就行了
- (void)menu:(WMZDropDownMenu *)menu didSelectRowAtDropIndexPath:(WMZDropIndexPath *)dropIndexPath dataIndexPath:(NSIndexPath *)indexpath data:(WMZDropTree *)data{
    if (dropIndexPath.section == 0 && dropIndexPath.row == 0) {
        //更新下一层 
        [menu updateDataConfig:@{@"rangeArr":[NSMutableArray arrayWithObjects:@"",@"",nil]} AtDropIndexPathSection:dropIndexPath.section AtDropIndexPathRow:dropIndexPath.row+1 AtIndexPathRow:0];
    }
}
