### ISSUE TITLE
下拉菜单起点位置的问题

### ISSUE THREAD

**Issue by xiaovvwork** [wwmz/WMZDropDownMenu#7]
你好，我发现如果视图控制器里有如下代码
`self.edgesForExtendedLayout = UIRectEdgeNone;`

然后设置
WMZDropDownMenu *menu = [[WMZDropDownMenu alloc] initWithFrame:CGRectMake(0, 0, Menu_Width, 40) withParam:param];

点击出现下拉菜单的时候，会以屏幕顶端作为起点往下滑出

**Comment by wwmz** [comment]
为什么要设置这个属性呢 设置这个属性你就要去把导航栏的高度加上呢
 加上这句 menu.menuOrignY = CGRectGetMaxY(menu.frame)+Menu_NavigationBar(导航栏高度);

**Comment by xiaovvwork** [comment]
> 为什么要设置这个属性呢 设置这个属性你就要去把导航栏的高度加上呢
> 加上这句 menu.menuOrignY = CGRectGetMaxY(menu.frame)+Menu_NavigationBar(导航栏高度);

因为旧项目是设置 edgesForExtendedLayout，让view的布局就是导航栏下面开始零点，
我就调整menuOrignY吧
