### ISSUE TITLE
WMZDropMenuBtn 的line颜色的设置

### ISSUE THREAD

**Issue by xiaovvwork** [wwmz/WMZDropDownMenu#8]
如果想设置WMZDropMenuBtn line的颜色，如何修改呢？如果在标题点击的代理方法
`- (void)menu:(WMZDropDownMenu *)menu didSelectTitleInSection:(NSInteger)section btn:(WMZDropMenuBtn *)selectBtn`

里面设置的话，不会有效果，因为我看到执行完代理之后，调用了 `showLine`，然后line的颜色又被改回去了

另外 `showLine` 传了一个config，demo里config都是穿空？

```
//点击代理
    if (self.delegate && [self.delegate respondsToSelector:@selector(menu:didSelectTitleInSection:btn:)]) {
        [self.delegate menu:self didSelectTitleInSection:sender.tag-1000 btn:sender];
    }
    
    if ([self.selectTitleBtn isSelected]&&self.param.wMenuLine) {
        [self.selectTitleBtn showLine:@{}];
    }else{
        [self.selectTitleBtn hidenLine];
    }

```

不知道是不是应该用另外一个返回按钮的代理方法

`- (NSDictionary*)menu:(WMZDropDownMenu *)menu  customTitleInSection:(NSInteger)section withTitleBtn:(WMZDropMenuBtn*)menuBtn`

但是这里返回的dictioary，请问应该是如何返回？demo没有找到如何使用，这个代理应该是只修改按钮也无法修改line

**Comment by wwmz** [comment]
这个line的颜色好像忘记放出来了呢 你可以去源码修改一下咯 就换个颜色就可以了 或者你可以放个属性出来接就好了 
在WMZDropMenuBtn类里  showLine的方法里

**Comment by xiaovvwork** [comment]
请问以后会更新么？pod引用的改代码总觉得不太好，有点强迫症，😄

**Comment by wwmz** [comment]
哈 会的 等有好几个问题要改的时候再更新呢 
self.selectTitleBtn showLine:@{}
这里的config本来传的就是控制line的 忘记了哈

**Comment by xiaovvwork** [comment]
好的，明白了
