### ISSUE TITLE
请问下我需要拿着 key 和 value 绑定 

### ISSUE THREAD

**Issue by qimiKond** [wwmz/WMZDropDownMenu#9]
请问下我需要拿着 key(需要展示出来的数据) 和 value(点击之后 得到的值 ) 绑定
我尝试 传入 ID    这样 取不到值. 请问是有什么固定格式或者参数吗

**Comment by wwmz** [comment]
在数据源的时候传入由字典组成的数据
@[
@"name":@"芝麻信用 极好(700分)以上",@"ID":@"11"},
@"name":@"芝麻信用 极好(700分)以上",@"ID":@"22"},
@"name":@"芝麻信用 极好(700分)以上",@"ID":@"33"},
]即可

WMZDropTree直接获取ID属性即可
模型里有的属性都可以通过字典传过来 自动识别 ，另外originalData是原来的传过来的字典

**Comment by KondLinqi** [comment]
谢谢
